from django.urls import path
from . import views

urlpatterns = [
    path('tasks', views.tasks, name='tasks'),
    path('create_task_page', views.create_task_page, name='create_task_page'),
    path('create_task', views.create_task, name='create_task'),
    path('define_project_timeframe', views.define_project_timeframe, name='define_project_timeframe'),
    path("change_project_page", views.change_project_page, name='change_project_page'),
    path('delete_task/<int:id>/', views.delete_task, name='delete_task'),
    path('add_dependency/<int:id>/', views.add_dependency, name='add_dependency'),
    path('add_dependency_page/<int:id>/', views.add_dependency_page, name='add_dependency_page'),
    path('delete_dependency/<int:task_id>/', views.delete_dependency, name='delete_dependency'),
    path('display_task/<int:id>/', views.display_task, name='display_task'),
    path('edit_task_page/<int:id>/', views.edit_task_page, name='edit_task_page'),
    path('task_team_update/<int:id>/', views.task_team_update, name='task_team_update'),
    path('task_loops_update/<int:id>/', views.task_loops_update, name='task_loops_update'),
    path('task_name_update/<int:id>/', views.task_name_update, name='task_name_update'),
    path('task_priority_update/<int:id>/', views.task_priority_update, name='task_priority_update'),
    path('task_approval_required_update/<int:id>/', views.task_approval_required_update, name='task_approval_required_update'),
    path('task_difficulty_update/<int:id>/', views.task_difficulty_update, name='task_difficulty_update'),
    path('timeline', views.timeline, name='timeline'),
    path('add_todo/<int:id>/', views.add_todo, name="add_todo"),
    path('todo_done_update/<int:id>/', views.todo_done_update, name="todo_done_update"),
    path('reload_timeline', views.reload_timeline, name="reload_timeline"),
    path('reload_tasks', views.reload_tasks, name="reload_tasks"),
    path('reload_all', views.reload_all, name="reload_all"),
    path('training_page', views.training_page, name='training_page'),
    path('add_dependency_training_page', views.add_dependency_training_page, name='add_dependency_training_page'),
    path('training', views.training, name='training'),
    path('define_current_date', views.define_current_date, name='define_current_date'),
    path('current_date_previous_date', views.current_date_previous_date, name='current_date_previous_date'),
    path('current_date_next_date', views.current_date_next_date, name='current_date_next_date'),
    path('calender', views.calender, name='calender'),
    path('reload_calender', views.reload_calender, name='reload_calender'),
    path('tasks_and_processes', views.tasks_and_processes, name="tasks_and_processes"),
    # path('create_task_page_v2', views.create_task_page_v2, name='create_task_page_v2'),
    path('create_process', views.create_process, name='create_process'),
    path('create_task_v2', views.create_task_v2, name='create_task_v2'),
    path('edit_task_page_v2/<int:task_id>', views.edit_task_page_v2, name="edit_task_page_v2"),
    path('create_process_page', views.create_process_page, name='create_process_page'),
    path('edit_process_page/<int:process_id>', views.edit_process_page, name='edit_process_page'),
    path("create_milestone/<int:process_id>", views.create_milestone, name='create_milestone'),
    path("process/<int:process_id>/milestones/reorder/", views.reorder_milestones, name="reorder_milestones"),
    path('connections', views.connections, name="connections"),
    path('graph/delete-dependency/', views.delete_dependency_graph_repr, name='delete_dependency_graph_repr'),

]