# Generated by Django 5.2.4 on 2025-07-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loops', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_index', models.IntegerField(default=0)),
                ('scheduled_date', models.DateField()),
                ('priority', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('approval_required', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(blank=True, null=True, to='distributor.taskloop')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributor.team'),
        ),
    ]
