# Generated by Django 5.2.4 on 2025-08-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='initial_dependencies',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='distributor.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributor.task'),
        ),
        migrations.AddField(
            model_name='taskloop',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.task'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='task_loop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributor.taskloop'),
        ),
        migrations.AddField(
            model_name='taskloopdependency',
            name='dependent_task_loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='distributor.taskloop'),
        ),
        migrations.AddField(
            model_name='taskloopdependency',
            name='master_task_loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='distributor.taskloop'),
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributor.task'),
        ),
        migrations.AlterUniqueTogether(
            name='taskloopdependency',
            unique_together={('master_task_loop', 'dependent_task_loop')},
        ),
    ]
