# Generated by Django 5.2.4 on 2025-07-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskloop',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='distributor.taskloop'),
        ),
    ]
