# Generated by Django 5.2.4 on 2025-08-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskloop',
            name='order_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
