# Generated by Django 5.2.4 on 2025-08-07 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_taskloop_order_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
