# Generated by Django 5.2.4 on 2025-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_project_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskloop',
            name='generated_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
