# Generated by Django 5.2.4 on 2025-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_rename_ending_date_project_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskloop',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='taskloop',
            name='defined_dependencies',
            field=models.ManyToManyField(blank=True, related_name='defined_dependencies_set', to='distributor.taskloop'),
        ),
        migrations.AddField(
            model_name='taskloop',
            name='generated_dependencies',
            field=models.ManyToManyField(blank=True, related_name='generated_dependencies_set', to='distributor.taskloop'),
        ),
    ]
