# Generated by Django 5.2.4 on 2025-08-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_taskloop_generated_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskloop',
            name='generated_deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='generated_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
