# Generated by Django 5.2.4 on 2025-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_remove_taskloop_dependencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='initial_dependencies',
            field=models.ManyToManyField(blank=True, to='distributor.task'),
        ),
    ]
