# Generated by Django 5.2.4 on 2025-08-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0006_remove_taskloop_generated_deadline_and_more'),
        ('users', '0005_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='users.team'),
        ),
    ]
