# Generated by Django 5.2.4 on 2025-07-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0006_task_initial_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
