# Generated by Django 5.2.4 on 2025-07-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0007_team_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
