# Generated by Django 5.2.4 on 2025-07-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0008_alter_team_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskloop',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
