# Generated by Django 5.2.4 on 2025-08-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0008_alter_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
