# Generated by Django 5.2.4 on 2025-07-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0010_alter_taskloop_loop_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskloop',
            old_name='defined_dependencies',
            new_name='cross_loop_dependencies',
        ),
        migrations.RenameField(
            model_name='taskloop',
            old_name='generated_dependencies',
            new_name='prior_loop_dependencies',
        ),
    ]
