# Generated by Django 5.2.4 on 2025-08-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0010_process_task_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='distributor.process'),
        ),
    ]
