# Generated by Django 5.2.4 on 2025-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0011_rename_defined_dependencies_taskloop_cross_loop_dependencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='initial_dependencies',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='distributor.task'),
        ),
    ]
