# Generated by Django 5.2.4 on 2025-08-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0011_alter_task_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_in_process',
            field=models.IntegerField(default=0),
        ),
    ]
