# Generated by Django 5.2.4 on 2025-08-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0013_rename_order_in_process_task_hierarchy_in_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
