# Generated by Django 5.2.4 on 2025-07-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0013_task_approval_required_task_difficulty_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskloop',
            name='order_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
