# Generated by Django 5.2.4 on 2025-07-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0014_taskloop_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskloop',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
