# Generated by Django 5.2.4 on 2025-08-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0014_alter_task_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presuccessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presuccessor_set', to='distributor.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_set', to='distributor.task')),
            ],
            options={
                'unique_together': {('presuccessor', 'successor')},
            },
        ),
    ]
