# Generated by Django 5.2.4 on 2025-08-11 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0015_taskdependency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='task',
            name='initial_dependencies',
        ),
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='required_by', through='distributor.TaskDependency', through_fields=('presuccessor', 'successor'), to='distributor.task'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='presuccessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='distributor.task'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='successor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='distributor.task'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('presuccessor', 'successor'), name='uniq_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('presuccessor', models.F('successor')), _negated=True), name='no_self_dependency'),
        ),
    ]
