# Generated by Django 5.2.4 on 2025-07-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0016_alter_taskloop_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskloop',
            name='defined_dependencies',
            field=models.ManyToManyField(blank=True, related_name='defined_dependencies_set', to='distributor.taskloop'),
        ),
        migrations.AlterField(
            model_name='taskloop',
            name='cross_loop_dependencies',
            field=models.ManyToManyField(blank=True, related_name='cross_loop_dependencies_set', to='distributor.taskloop'),
        ),
    ]
