# Generated by Django 5.2.4 on 2025-08-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0016_alter_taskdependency_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dependencies',
            new_name='initial_dependencies',
        ),
    ]
