# Generated by Django 5.2.4 on 2025-08-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0017_rename_dependencies_task_initial_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdependency',
            name='presuccessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presuccessor_set', to='distributor.task'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='successor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_set', to='distributor.task'),
        ),
    ]
