# Generated by Django 5.2.4 on 2025-07-31 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0017_taskloop_defined_dependencies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributor.task')),
                ('task_loop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributor.taskloop')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distributor.team')),
            ],
        ),
    ]
