# Generated by Django 5.2.4 on 2025-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0018_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
