# Generated by Django 5.2.4 on 2025-07-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0019_activitylog_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
