# Generated by Django 5.2.4 on 2025-07-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0020_activitylog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskloop',
            name='magnitude',
            field=models.FloatField(default=0),
        ),
    ]
