# Generated by Django 5.2.4 on 2025-08-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0023_project_order_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLoopDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('defined', 'Defined'), ('prior_loop', 'Prior Loop'), ('cross_loop', 'Cross Loop')], max_length=50)),
                ('weight', models.FloatField(default=0)),
                ('dependent_task_loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='distributor.taskloop')),
                ('master_task_loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='distributor.taskloop')),
            ],
            options={
                'unique_together': {('master_task_loop', 'dependent_task_loop')},
            },
        ),
    ]
