# Generated by Django 5.2.4 on 2025-08-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0024_taskloopdependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskloopdependency',
            name='dependent_task_loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='distributor.taskloop'),
        ),
        migrations.AlterField(
            model_name='taskloopdependency',
            name='master_task_loop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='distributor.taskloop'),
        ),
    ]
