# Generated by Django 5.2.4 on 2025-08-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0025_alter_taskloopdependency_dependent_task_loop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskloop',
            name='cross_loop_dependencies',
        ),
        migrations.RemoveField(
            model_name='taskloop',
            name='defined_dependencies',
        ),
        migrations.RemoveField(
            model_name='taskloop',
            name='prior_loop_dependencies',
        ),
    ]
